### ISSUE TITLE
Lag

### ISSUE THREAD

**Issue by YasinK2003** [ItsToxicGG/PlayerlyAPI#11]
0.02%	15.79%	7.90 ms	7.90 ms	0.0	1.0	0.0	Task: Toxic\task\SessionTimeTask(interval 1200)

just by 2 players loading in it already causes lag, i think we need a new method to calculate session time,

an idea would be to update session time when that information is requested in the database

**Comment by ItsToxicGG** [comment]
Hello, ive not notice this, because i only tested with 1 player but surely ill fix this

**Comment by ItsToxicGG** [comment]
@YasinK2003 try latest ver tell me if this was resloved
