### ISSUE TITLE
Missing port section

### ISSUE THREAD

**Issue by YasinK2003** [ItsToxicGG/PlayerlyAPI#8]

**Comment by YasinK2003** [comment]
it says connection refused, probobly because i cant fill in the port in my config

**Comment by ItsToxicGG** [comment]
Hello, thanks for the issue, will be implemented in 2 mins

**Comment by ItsToxicGG** [comment]
wait are you sure that you using the details because with me its working fine
remember to change the config.yml to the right things to connect the thing in config is just an example

**Comment by ItsToxicGG** [comment]
This Was implemented in the new commit
