### ISSUE TITLE
Option to disable features

### ISSUE THREAD

**Issue by YasinK2003** [ItsToxicGG/PlayerlyAPI#9]
You should add an option to goggle one some stuff just like you did with the auth system,

thats because this plugin overwrites lets say a mute plugin i got as example

**Comment by ItsToxicGG** [comment]
Great idea, this was a thing once i was busy with the plugin a few days ago but removed it once, thanks for the feedback check for updates, ill make it optional

**Comment by ItsToxicGG** [comment]
This was implemented in the latest commits, when i implement new systems in the future they will also be optional if the player is using an another plugin so it wont override that plugin also i change the permissions to be unqiue to not get not be simmilar to any other plugins permission example:
```md
# old permisisons
mute.command
# new permissions
toxic.mute.command
```
as you can see the new permissions has toxic infront of it and old not which most plugin creators most likely use mute.permission so i changed that so it wont override any other plugins!
